const CURATED_SEASONAL_CANDIDATES = [
  // spring
  { season: 'spring', query: '석촌호수', keyword: '벚꽃 명소' },
  { season: 'spring', query: '서울숲', keyword: '튤립 공원' },
  { season: 'spring', query: '경복궁', keyword: '벚꽃 명소' },
  { season: 'spring', query: '창경궁', keyword: '벚꽃 명소' },
  { season: 'spring', query: '자유공원', keyword: '벚꽃 명소' },
  { season: 'spring', query: '무심천 벚꽃거리', keyword: '벚꽃 명소' },
  { season: 'spring', query: '보문호', keyword: '벚꽃 명소' },
  { season: 'spring', query: '여좌천', keyword: '벚꽃 명소' },
  { season: 'spring', query: '하동십리벚꽃길', keyword: '벚꽃길' },
  { season: 'spring', query: '화개장터', keyword: '벚꽃 명소' },
  { season: 'spring', query: '구례산수유마을', keyword: '개나리 명소' },
  { season: 'spring', query: '응봉산', keyword: '개나리 명소' },
  { season: 'spring', query: '불국사', keyword: '겹벚꽃 명소' },
  { season: 'spring', query: '남지 유채꽃단지', keyword: '유채꽃밭' },
  { season: 'spring', query: '산방산 유채꽃밭', keyword: '유채꽃밭' },
  { season: 'spring', query: '보롬왓', keyword: '튤립 공원' },
  { season: 'spring', query: '고창 청농원', keyword: '작약 명소' },
  { season: 'spring', query: '이월드', keyword: '튤립 축제' },
  { season: 'spring', query: '태안 세계튤립꽃박람회', keyword: '튤립 축제' },
  { season: 'spring', query: '황매산군립공원', keyword: '철쭉 명소' },
  { season: 'spring', query: '서울대공원', keyword: '벚꽃 명소' },
  { season: 'spring', query: '대릉원', keyword: '벚꽃 명소' },
  { season: 'spring', query: '청남대', keyword: '벚꽃 명소' },
  { season: 'spring', query: '선암사', keyword: '겹벚꽃 명소' },
  { season: 'spring', query: '맹방유채꽃마을', keyword: '유채꽃밭' },
  { season: 'spring', query: '유기방가옥', keyword: '수선화 명소' },
  { season: 'spring', query: '여의서로', keyword: '벚꽃 명소' },
  { season: 'spring', query: '전농로 왕벚꽃거리', keyword: '벚꽃 명소' },
  { season: 'spring', query: '경화역공원', keyword: '벚꽃 명소' },
  { season: 'spring', query: '반곡지', keyword: '복사꽃 명소' },
  { season: 'spring', query: '원미산 진달래동산', keyword: '진달래 명소' },
  { season: 'spring', query: '고려산', keyword: '진달래 명소' },
  { season: 'spring', query: '강릉 경포대', keyword: '벚꽃 명소' },
  { season: 'spring', query: '대청호 벚꽃길', keyword: '벚꽃길' },
  { season: 'spring', query: '서울 어린이대공원', keyword: '튤립 명소' },
  { season: 'spring', query: '마노르블랑', keyword: '유채꽃 명소' },

  // summer
  { season: 'summer', query: '태화강국가정원', keyword: '수국 명소' },
  { season: 'summer', query: '아침고요수목원', keyword: '수국 명소' },
  { season: 'summer', query: '제이드가든', keyword: '수국 명소' },
  { season: 'summer', query: '오동도', keyword: '동백 명소' },
  { season: 'summer', query: '시흥 연꽃테마파크', keyword: '연꽃 명소' },
  { season: 'summer', query: '함안 연꽃테마파크', keyword: '연꽃 명소' },
  { season: 'summer', query: '배곧한울공원', keyword: '해바라기 명소' },
  { season: 'summer', query: '안성팜랜드', keyword: '해바라기 명소' },
  { season: 'summer', query: '허브아일랜드', keyword: '라벤더 축제' },
  { season: 'summer', query: '제주허브동산', keyword: '라벤더 축제' },
  { season: 'summer', query: '서울대공원 장미원', keyword: '장미 축제' },
  { season: 'summer', query: '에버랜드 장미원', keyword: '장미 축제' },
  { season: 'summer', query: '곡성 섬진강기차마을 장미공원', keyword: '장미 축제' },
  { season: 'summer', query: '순천만국가정원', keyword: '백일홍 명소' },
  { season: 'summer', query: '국립생태원', keyword: '안개꽃 명소' },
  { season: 'summer', query: '비체올린', keyword: '능소화 명소' },
  { season: 'summer', query: '담양 메타세쿼이아길', keyword: '능소화 명소' },
  { season: 'summer', query: '제주휴애리', keyword: '수국 축제' },
  { season: 'summer', query: '청산수목원', keyword: '연꽃 명소' },
  { season: 'summer', query: '부천 백만송이장미원', keyword: '장미 축제' },
  { season: 'summer', query: '울산대공원 장미원', keyword: '장미 명소' },
  { season: 'summer', query: '거제 저구항 수국길', keyword: '수국 명소' },
  { season: 'summer', query: '보롬왓', keyword: '해바라기 명소' },
  { season: 'summer', query: '안면도 꽃지해안공원', keyword: '해바라기 명소' },
  { season: 'summer', query: '공주 유구색동수국정원', keyword: '수국 축제' },
  { season: 'summer', query: '서울식물원', keyword: '수국 명소' },
  { season: 'summer', query: '북서울꿈의숲', keyword: '수국 명소' },
  { season: 'summer', query: '무안 회산백련지', keyword: '연꽃 축제' },
  { season: 'summer', query: '부여 궁남지', keyword: '연꽃 명소' },
  { season: 'summer', query: '양평 세미원', keyword: '연꽃 명소' },
  { season: 'summer', query: '제주 마노르블랑', keyword: '수국 명소' },
  { season: 'summer', query: '장생포 고래문화마을', keyword: '수국 축제' },
  { season: 'summer', query: '서울대공원', keyword: '장미원' },
  { season: 'summer', query: '고양 호수공원', keyword: '연꽃 명소' },
  { season: 'summer', query: '월드컵공원', keyword: '수국 명소' },

  // autumn
  { season: 'autumn', query: '올림픽공원', keyword: '코스모스 공원' },
  { season: 'autumn', query: '하동 북천 코스모스 메밀꽃 축제', keyword: '코스모스 축제' },
  { season: 'autumn', query: '드라마촬영장 핑크뮬리', keyword: '핑크뮬리 명소' },
  { season: 'autumn', query: '양주 나리공원', keyword: '핑크뮬리 공원' },
  { season: 'autumn', query: '경주 첨성대', keyword: '핑크뮬리 명소' },
  { season: 'autumn', query: '명성산', keyword: '억새 명소' },
  { season: 'autumn', query: '오서산', keyword: '억새 명소' },
  { season: 'autumn', query: '천관산', keyword: '억새 명소' },
  { season: 'autumn', query: '서울억새축제', keyword: '억새 축제' },
  { season: 'autumn', query: '민둥산', keyword: '억새 축제' },
  { season: 'autumn', query: '효석문화마을', keyword: '메밀꽃 축제' },
  { season: 'autumn', query: '봉평 메밀꽃밭', keyword: '메밀꽃 명소' },
  { season: 'autumn', query: '구절초지방정원', keyword: '구절초 축제' },
  { season: 'autumn', query: '정읍 구절초지방정원', keyword: '구절초 축제' },
  { season: 'autumn', query: '함평엑스포공원', keyword: '국화 축제' },
  { season: 'autumn', query: '익산 천만송이국화축제', keyword: '국화 축제' },
  { season: 'autumn', query: '시흥갯골생태공원', keyword: '핑크뮬리 명소' },
  { season: 'autumn', query: '안산갈대습지공원', keyword: '억새 명소' },
  { season: 'autumn', query: '허브아일랜드', keyword: '핑크뮬리 명소' },
  { season: 'autumn', query: '태화강국가정원', keyword: '국화 축제' },
  { season: 'autumn', query: '정읍 구절초테마공원', keyword: '구절초 축제' },
  { season: 'autumn', query: '황매산군립공원', keyword: '억새 명소' },
  { season: 'autumn', query: '합천 신소양체육공원', keyword: '핑크뮬리 명소' },
  { season: 'autumn', query: '하동 북천 메밀꽃밭', keyword: '메밀꽃 명소' },
  { season: 'autumn', query: '하늘공원', keyword: '억새 명소' },
  { season: 'autumn', query: '서울숲', keyword: '코스모스 명소' },
  { season: 'autumn', query: '양재천', keyword: '코스모스 명소' },
  { season: 'autumn', query: '안성팜랜드', keyword: '코스모스 명소' },
  { season: 'autumn', query: '영남알프스 간월재', keyword: '억새 명소' },
  { season: 'autumn', query: '소래습지생태공원', keyword: '핑크뮬리 명소' },
  { season: 'autumn', query: '제주 따라비오름', keyword: '억새 명소' },
  { season: 'autumn', query: '마산가고파국화축제', keyword: '국화 축제' },
  { season: 'autumn', query: '함안 강나루생태공원', keyword: '핑크뮬리 명소' },
  { season: 'autumn', query: '구리한강시민공원', keyword: '코스모스 명소' },

  // winter
  { season: 'winter', query: '카멜리아힐', keyword: '동백꽃 명소' },
  { season: 'winter', query: '오동도', keyword: '동백꽃 명소' },
  { season: 'winter', query: '선운사', keyword: '동백꽃 명소' },
  { season: 'winter', query: '위미 동백군락지', keyword: '동백꽃 명소' },
  { season: 'winter', query: '제주동백수목원', keyword: '동백꽃 명소' },
  { season: 'winter', query: '휴애리자연생활공원', keyword: '수선화 축제' },
  { season: 'winter', query: '한림공원', keyword: '수선화 명소' },
  { season: 'winter', query: '노리매', keyword: '매화 명소' },
  { season: 'winter', query: '광양 매화마을', keyword: '매화 축제' },
  { season: 'winter', query: '제주허브동산', keyword: '시클라멘 명소' },
  { season: 'winter', query: '아침고요수목원', keyword: '복수초 명소' },
  { season: 'winter', query: '천리포수목원', keyword: '크리스마스로즈 명소' },
  { season: 'winter', query: '제주카멜리아힐', keyword: '동백축제' },
  { season: 'winter', query: '휴애리 동백축제', keyword: '동백꽃 명소' },
  { season: 'winter', query: '마노르블랑', keyword: '동백꽃 명소' },
  { season: 'winter', query: '거제 지심도', keyword: '동백꽃 명소' },
  { season: 'winter', query: '오륙도해맞이공원', keyword: '수선화 명소' },
  { season: 'winter', query: '광양매화축제장', keyword: '매화 축제' },
  { season: 'winter', query: '노리매공원', keyword: '매화 명소' },
  { season: 'winter', query: '동백포레스트', keyword: '동백꽃 명소' },
  { season: 'winter', query: '휴애리 자연생활공원', keyword: '수선화 축제' },
  { season: 'winter', query: '신안 선도 수선화정원', keyword: '수선화 명소' },
  { season: 'winter', query: '노리매 매화공원', keyword: '매화 명소' },
  { season: 'winter', query: '다산초당', keyword: '동백꽃 명소' },
  { season: 'winter', query: '제주 허브동산', keyword: '시클라멘 명소' },
  { season: 'winter', query: '천리포수목원', keyword: '겨울꽃 명소' },
  { season: 'winter', query: '한림공원', keyword: '수선화 축제' },
  { season: 'winter', query: '오륙도해맞이공원', keyword: '수선화 명소' },
  { season: 'winter', query: '강진 다산초당', keyword: '동백꽃 명소' },
];

module.exports = { CURATED_SEASONAL_CANDIDATES };
