/* eslint-disable @typescript-eslint/no-require-imports */
const { createClient } = require('@supabase/supabase-js');
const { loadLocalEnv } = require('./loadEnv.cjs');

const CURATED_SPOTS = [
  // 봄
  {
    external_place_id: 'curated:yeouiseoro',
    name: '여의서로',
    address: '서울 영등포구 여의도동',
    lat: 37.5269,
    lng: 126.9235,
    flower_types: ['cherry'],
    category: 'street',
    peak_month_start: 4,
    peak_month_end: 4,
    has_parking: false,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:gyeonghwa-station',
    name: '경화역',
    address: '경남 창원시 진해구 경화동',
    lat: 35.1561,
    lng: 128.6939,
    flower_types: ['cherry'],
    category: 'street',
    peak_month_start: 3,
    peak_month_end: 4,
    has_parking: false,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:gwangyang-maehwa',
    name: '광양 매화마을',
    address: '전남 광양시 다압면 지막1길 55',
    lat: 35.0934,
    lng: 127.6924,
    flower_types: ['plum'],
    category: 'farm',
    peak_month_start: 3,
    peak_month_end: 3,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:cheoljjuk-dongsan',
    name: '철쭉동산',
    address: '경기 군포시 산본동',
    lat: 37.3677,
    lng: 126.9344,
    flower_types: ['azalea'],
    category: 'park',
    peak_month_start: 4,
    peak_month_end: 5,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:ilsan-lake-park',
    name: '일산호수공원',
    address: '경기 고양시 일산동구 장항동 906',
    lat: 37.6587,
    lng: 126.7666,
    flower_types: ['tulip'],
    category: 'park',
    peak_month_start: 4,
    peak_month_end: 5,
    has_parking: true,
    photo_spot: true,
    has_night_light: true,
  },
  {
    external_place_id: 'curated:korea-flower-park',
    name: '코리아플라워파크',
    address: '충남 태안군 안면읍 꽃지해안로 400',
    lat: 36.5047,
    lng: 126.3298,
    flower_types: ['tulip'],
    category: 'park',
    peak_month_start: 4,
    peak_month_end: 5,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:daejeo-eco-park',
    name: '대저생태공원',
    address: '부산 강서구 대저1동 1-5',
    lat: 35.2121,
    lng: 128.9594,
    flower_types: ['rape'],
    category: 'river',
    peak_month_start: 4,
    peak_month_end: 4,
    has_parking: true,
    photo_spot: true,
    pet_friendly: true,
  },
  {
    external_place_id: 'curated:noksan-ro',
    name: '녹산로',
    address: '제주 서귀포시 표선면 가시리',
    lat: 33.3834,
    lng: 126.7701,
    flower_types: ['rape'],
    category: 'street',
    peak_month_start: 3,
    peak_month_end: 4,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:hwangmaesan',
    name: '황매산',
    address: '경남 합천군 가회면 둔내리 산219',
    lat: 35.4867,
    lng: 127.9751,
    flower_types: ['azalea'],
    category: 'mountain',
    peak_month_start: 5,
    peak_month_end: 5,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:cheongnamdae',
    name: '청남대',
    address: '충북 청주시 상당구 문의면 청남대길 646',
    lat: 36.4638,
    lng: 127.4916,
    flower_types: ['cherry'],
    category: 'park',
    peak_month_start: 4,
    peak_month_end: 4,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:daereungwon',
    name: '대릉원',
    address: '경북 경주시 계림로 9',
    lat: 35.8381,
    lng: 129.2111,
    flower_types: ['cherry'],
    category: 'park',
    peak_month_start: 4,
    peak_month_end: 4,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:namji-rape',
    name: '남지 유채꽃단지',
    address: '경남 창녕군 남지읍 남지강변길 177',
    lat: 35.5408,
    lng: 128.4957,
    flower_types: ['rape'],
    category: 'river',
    peak_month_start: 4,
    peak_month_end: 4,
    has_parking: true,
    photo_spot: true,
  },

  // 여름
  {
    external_place_id: 'curated:manoirblanc',
    name: '마노르블랑',
    address: '제주 서귀포시 안덕면 일주서로2100번길 46',
    lat: 33.2532,
    lng: 126.3499,
    flower_types: ['hydrangea'],
    category: 'cafe',
    peak_month_start: 6,
    peak_month_end: 7,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:hueree',
    name: '휴애리 자연생활공원',
    address: '제주 서귀포시 남원읍 신례동로 256',
    lat: 33.3088,
    lng: 126.6345,
    flower_types: ['hydrangea'],
    category: 'park',
    peak_month_start: 6,
    peak_month_end: 7,
    has_parking: true,
    photo_spot: true,
    pet_friendly: true,
  },
  {
    external_place_id: 'curated:bicheollin',
    name: '비체올린',
    address: '제주 제주시 한경면 판조로 253-6',
    lat: 33.3287,
    lng: 126.2683,
    flower_types: ['neungsohwa'],
    category: 'park',
    peak_month_start: 6,
    peak_month_end: 7,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:jangsaengpo',
    name: '장생포 고래문화특구',
    address: '울산 남구 장생포고래로 244',
    lat: 35.5059,
    lng: 129.3834,
    flower_types: ['hydrangea'],
    category: 'park',
    peak_month_start: 6,
    peak_month_end: 6,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:yugu-hydrangea',
    name: '유구색동수국정원',
    address: '충남 공주시 유구읍 창말길 44',
    lat: 36.5555,
    lng: 126.9377,
    flower_types: ['hydrangea'],
    category: 'park',
    peak_month_start: 6,
    peak_month_end: 6,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:guwau-village',
    name: '구와우마을',
    address: '강원 태백시 구와우길 38-20',
    lat: 37.1508,
    lng: 128.9793,
    flower_types: ['sunflower'],
    category: 'farm',
    peak_month_start: 7,
    peak_month_end: 8,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:gungnamji',
    name: '궁남지',
    address: '충남 부여군 부여읍 궁남로 52',
    lat: 36.2757,
    lng: 126.9166,
    flower_types: ['lotus'],
    category: 'river',
    peak_month_start: 7,
    peak_month_end: 7,
    has_parking: true,
    photo_spot: true,
    has_night_light: true,
  },
  {
    external_place_id: 'curated:hoesan-baekryeonji',
    name: '회산백련지',
    address: '전남 무안군 일로읍 복룡리 1',
    lat: 34.8478,
    lng: 126.4744,
    flower_types: ['lotus'],
    category: 'river',
    peak_month_start: 7,
    peak_month_end: 8,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:semiwon',
    name: '세미원',
    address: '경기 양평군 양서면 양수로 93',
    lat: 37.5458,
    lng: 127.3255,
    flower_types: ['lotus'],
    category: 'botanical',
    peak_month_start: 7,
    peak_month_end: 8,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:hwadamsup',
    name: '화담숲',
    address: '경기 광주시 도척면 도척윗로 278-1',
    lat: 37.3379,
    lng: 127.2838,
    flower_types: ['hydrangea'],
    category: 'botanical',
    peak_month_start: 6,
    peak_month_end: 7,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:suncheonman-garden',
    name: '순천만국가정원',
    address: '전남 순천시 국가정원1호길 47',
    lat: 34.9491,
    lng: 127.5095,
    flower_types: ['zinnia'],
    category: 'botanical',
    peak_month_start: 6,
    peak_month_end: 10,
    has_parking: true,
    photo_spot: true,
    has_night_light: true,
  },
  {
    external_place_id: 'curated:national-ecology-center',
    name: '국립생태원',
    address: '충남 서천군 마서면 금강로 1210',
    lat: 36.0277,
    lng: 126.7098,
    flower_types: ['lavender'],
    category: 'botanical',
    peak_month_start: 8,
    peak_month_end: 8,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:morning-calm',
    name: '아침고요수목원',
    address: '경기 가평군 상면 수목원로 432',
    lat: 37.7438,
    lng: 127.3526,
    flower_types: ['hydrangea'],
    category: 'botanical',
    peak_month_start: 6,
    peak_month_end: 7,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:siheung-lotus',
    name: '시흥 연꽃테마파크',
    address: '경기 시흥시 관곡지로 139',
    lat: 37.4024,
    lng: 126.8052,
    flower_types: ['lotus'],
    category: 'river',
    peak_month_start: 7,
    peak_month_end: 8,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:herb-island',
    name: '허브아일랜드',
    address: '경기 포천시 신북면 청신로947번길 51',
    lat: 37.9658,
    lng: 127.1404,
    flower_types: ['lavender'],
    category: 'park',
    peak_month_start: 6,
    peak_month_end: 8,
    has_parking: true,
    photo_spot: true,
    has_night_light: true,
  },
  {
    external_place_id: 'curated:bucheon-rose',
    name: '부천 백만송이장미원',
    address: '경기 부천시 원미구 성곡로63번길 99',
    lat: 37.5215,
    lng: 126.8181,
    flower_types: ['rose'],
    category: 'park',
    peak_month_start: 5,
    peak_month_end: 6,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:everland-rose',
    name: '에버랜드 장미원',
    address: '경기 용인시 처인구 포곡읍 에버랜드로 199',
    lat: 37.2952,
    lng: 127.2029,
    flower_types: ['rose'],
    category: 'park',
    peak_month_start: 5,
    peak_month_end: 6,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:boromwat',
    name: '보롬왓',
    address: '제주 서귀포시 표선면 번영로 2350-104',
    lat: 33.3964,
    lng: 126.7529,
    flower_types: ['sunflower'],
    category: 'farm',
    peak_month_start: 7,
    peak_month_end: 8,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:haman-lotus',
    name: '함안 연꽃테마파크',
    address: '경남 함안군 가야읍 왕궁길 38-20',
    lat: 35.2723,
    lng: 128.4085,
    flower_types: ['lotus'],
    category: 'river',
    peak_month_start: 7,
    peak_month_end: 8,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:ulsan-rose-garden',
    name: '울산대공원 장미원',
    address: '울산 남구 대공원로 94',
    lat: 35.5387,
    lng: 129.2948,
    flower_types: ['rose'],
    category: 'park',
    peak_month_start: 5,
    peak_month_end: 6,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:cheongsan-botanical',
    name: '청산수목원',
    address: '충남 태안군 남면 연꽃길 70',
    lat: 36.6706,
    lng: 126.2861,
    flower_types: ['lotus'],
    category: 'botanical',
    peak_month_start: 7,
    peak_month_end: 8,
    has_parking: true,
    photo_spot: true,
  },

  // 가을
  {
    external_place_id: 'curated:gwangneung-arboretum-foliage',
    name: '광릉수목원',
    address: '경기 포천시 소흘읍 광릉수목원로 415',
    lat: 37.7521,
    lng: 127.1643,
    flower_types: ['foliage'],
    category: 'botanical',
    peak_month_start: 10,
    peak_month_end: 11,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:naejangsan-foliage',
    name: '내장산국립공원',
    address: '전북 정읍시 내장산로 936',
    lat: 35.4835,
    lng: 126.8876,
    flower_types: ['foliage'],
    category: 'mountain',
    peak_month_start: 10,
    peak_month_end: 11,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:seoraksan-foliage',
    name: '설악산국립공원',
    address: '강원 속초시 설악산로 833',
    lat: 38.1194,
    lng: 128.4656,
    flower_types: ['foliage'],
    category: 'mountain',
    peak_month_start: 10,
    peak_month_end: 10,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:namiseom-foliage',
    name: '남이섬',
    address: '강원 춘천시 남산면 남이섬길 1',
    lat: 37.7915,
    lng: 127.5257,
    flower_types: ['foliage'],
    category: 'park',
    peak_month_start: 10,
    peak_month_end: 11,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:juwangsan-foliage',
    name: '주왕산국립공원',
    address: '경북 청송군 주왕산면 공원길 169-7',
    lat: 36.3935,
    lng: 129.1605,
    flower_types: ['foliage'],
    category: 'mountain',
    peak_month_start: 10,
    peak_month_end: 11,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:hwadamsup-foliage',
    name: '화담숲 단풍길',
    address: '경기 광주시 도척면 도척윗로 278-1',
    lat: 37.3379,
    lng: 127.2838,
    flower_types: ['foliage'],
    category: 'botanical',
    peak_month_start: 10,
    peak_month_end: 11,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:deoksugung-foliage',
    name: '덕수궁 돌담길',
    address: '서울 중구 세종대로 99',
    lat: 37.5658,
    lng: 126.9751,
    flower_types: ['foliage'],
    category: 'street',
    peak_month_start: 10,
    peak_month_end: 11,
    has_parking: false,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:haneul-park',
    name: '하늘공원',
    address: '서울 마포구 하늘공원로 95',
    lat: 37.5694,
    lng: 126.8786,
    flower_types: ['silvergrass'],
    category: 'park',
    peak_month_start: 10,
    peak_month_end: 10,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:mindungsan',
    name: '민둥산',
    address: '강원 정선군 남면 무릉리',
    lat: 37.2422,
    lng: 128.7757,
    flower_types: ['silvergrass'],
    category: 'mountain',
    peak_month_start: 9,
    peak_month_end: 10,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:bongpyeong-buckwheat',
    name: '봉평 메밀꽃밭',
    address: '강원 평창군 봉평면 효석문학길 193-1',
    lat: 37.6123,
    lng: 128.3792,
    flower_types: ['buckwheat'],
    category: 'farm',
    peak_month_start: 9,
    peak_month_end: 9,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:hampyeong-expo-park',
    name: '함평엑스포공원',
    address: '전남 함평군 함평읍 곤재로 27',
    lat: 35.0646,
    lng: 126.5189,
    flower_types: ['chrysanthemum'],
    category: 'park',
    peak_month_start: 10,
    peak_month_end: 11,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:yangju-nari-park',
    name: '양주 나리공원',
    address: '경기 양주시 광사동 812',
    lat: 37.8013,
    lng: 127.0813,
    flower_types: ['pinkmuhly'],
    category: 'park',
    peak_month_start: 9,
    peak_month_end: 10,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:olympic-park-wildflower',
    name: '올림픽공원 들꽃마루',
    address: '서울 송파구 올림픽로 424',
    lat: 37.5208,
    lng: 127.1214,
    flower_types: ['cosmos'],
    category: 'park',
    peak_month_start: 9,
    peak_month_end: 10,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:myeongseongsan',
    name: '명성산',
    address: '경기 포천시 영북면 산정리',
    lat: 38.1092,
    lng: 127.3201,
    flower_types: ['silvergrass'],
    category: 'mountain',
    peak_month_start: 10,
    peak_month_end: 10,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:siheung-gaetgol',
    name: '시흥갯골생태공원',
    address: '경기 시흥시 동서로 287',
    lat: 37.3906,
    lng: 126.7805,
    flower_types: ['pinkmuhly'],
    category: 'park',
    peak_month_start: 9,
    peak_month_end: 10,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:jeongeup-gujeolcho',
    name: '정읍 구절초지방정원',
    address: '전북 정읍시 산내면 청정로 926-79',
    lat: 35.5717,
    lng: 126.8857,
    flower_types: ['chrysanthemum'],
    category: 'park',
    peak_month_start: 10,
    peak_month_end: 10,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:taehwagang-garden',
    name: '태화강국가정원',
    address: '울산 중구 태화강국가정원길 154',
    lat: 35.5511,
    lng: 129.2974,
    flower_types: ['chrysanthemum'],
    category: 'park',
    peak_month_start: 10,
    peak_month_end: 11,
    has_parking: true,
    photo_spot: true,
    has_night_light: true,
  },
  {
    external_place_id: 'curated:gyeongju-cheomseongdae',
    name: '경주 첨성대',
    address: '경북 경주시 인왕동 839-1',
    lat: 35.8347,
    lng: 129.2191,
    flower_types: ['pinkmuhly'],
    category: 'park',
    peak_month_start: 9,
    peak_month_end: 10,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:oser-san',
    name: '오서산',
    address: '충남 보령시 청소면 성연리',
    lat: 36.4238,
    lng: 126.5799,
    flower_types: ['silvergrass'],
    category: 'mountain',
    peak_month_start: 10,
    peak_month_end: 10,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:cheonkwansan',
    name: '천관산',
    address: '전남 장흥군 관산읍 옥당리',
    lat: 34.5074,
    lng: 126.9183,
    flower_types: ['silvergrass'],
    category: 'mountain',
    peak_month_start: 10,
    peak_month_end: 10,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:hyoseok-village',
    name: '효석문화마을',
    address: '강원 평창군 봉평면 이효석길 157',
    lat: 37.6121,
    lng: 128.3747,
    flower_types: ['buckwheat'],
    category: 'farm',
    peak_month_start: 9,
    peak_month_end: 9,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:hapcheon-pinkmuhly',
    name: '합천 신소양체육공원',
    address: '경남 합천군 합천읍 영창리 898',
    lat: 35.5626,
    lng: 128.1665,
    flower_types: ['pinkmuhly'],
    category: 'park',
    peak_month_start: 9,
    peak_month_end: 10,
    has_parking: true,
    photo_spot: true,
  },

  // 겨울
  {
    external_place_id: 'curated:camellia-hill',
    name: '카멜리아힐',
    address: '제주 서귀포시 안덕면 병악로 166',
    lat: 33.2897,
    lng: 126.3682,
    flower_types: ['camellia'],
    category: 'botanical',
    peak_month_start: 12,
    peak_month_end: 2,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:hallim-park',
    name: '한림공원',
    address: '제주 제주시 한림읍 한림로 300',
    lat: 33.3897,
    lng: 126.2392,
    flower_types: ['narcissus'],
    category: 'botanical',
    peak_month_start: 12,
    peak_month_end: 2,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:seonunsa',
    name: '선운사',
    address: '전북 고창군 아산면 선운사로 250',
    lat: 35.4795,
    lng: 126.5853,
    flower_types: ['camellia'],
    category: 'temple',
    peak_month_start: 12,
    peak_month_end: 3,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:jisimdo',
    name: '거제 지심도',
    address: '경남 거제시 일운면 지세포리',
    lat: 34.8185,
    lng: 128.7521,
    flower_types: ['camellia'],
    category: 'etc',
    peak_month_start: 12,
    peak_month_end: 3,
    has_parking: false,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:oryukdo-narcissus',
    name: '오륙도해맞이공원',
    address: '부산 남구 용호동 산196-3',
    lat: 35.1016,
    lng: 129.1229,
    flower_types: ['narcissus'],
    category: 'park',
    peak_month_start: 12,
    peak_month_end: 2,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:norimae',
    name: '노리매',
    address: '제주 서귀포시 대정읍 중산간서로 2260-15',
    lat: 33.2893,
    lng: 126.2872,
    flower_types: ['plum'],
    category: 'park',
    peak_month_start: 2,
    peak_month_end: 3,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:wimi-camellia',
    name: '위미 동백군락지',
    address: '제주 서귀포시 남원읍 위미리 929',
    lat: 33.2745,
    lng: 126.6622,
    flower_types: ['camellia'],
    category: 'etc',
    peak_month_start: 12,
    peak_month_end: 2,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:jeju-camellia-garden',
    name: '제주동백수목원',
    address: '제주 서귀포시 남원읍 위미중앙로300번길 15',
    lat: 33.2723,
    lng: 126.6675,
    flower_types: ['camellia'],
    category: 'botanical',
    peak_month_start: 12,
    peak_month_end: 2,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:camellia-forest',
    name: '동백포레스트',
    address: '제주 서귀포시 남원읍 태위로 929',
    lat: 33.2895,
    lng: 126.7116,
    flower_types: ['camellia'],
    category: 'etc',
    peak_month_start: 12,
    peak_month_end: 2,
    has_parking: true,
    photo_spot: true,
  },
  {
    external_place_id: 'curated:hueree-camellia',
    name: '휴애리 동백축제',
    address: '제주 서귀포시 남원읍 신례동로 256',
    lat: 33.3088,
    lng: 126.6345,
    flower_types: ['camellia'],
    category: 'park',
    peak_month_start: 11,
    peak_month_end: 2,
    has_parking: true,
    photo_spot: true,
  },
];

function normalizeKey(name, address) {
  return `${(name || '').trim().toLowerCase()}::${(address || '').trim().toLowerCase()}`;
}

async function syncCuratedSpots(supabase, rows) {
  const externalIds = rows.map((row) => row.external_place_id);
  const names = rows.map((row) => row.name);

  const { data: existingByExternal, error: externalError } = await supabase
    .from('flower_spots')
    .select('id, external_place_id, name, address')
    .in('external_place_id', externalIds);

  if (externalError) throw externalError;

  const { data: existingByName, error: nameError } = await supabase
    .from('flower_spots')
    .select('id, external_place_id, name, address')
    .in('name', names);

  if (nameError) throw nameError;

  const externalMap = new Map(
    (existingByExternal ?? []).map((row) => [row.external_place_id, row.id]),
  );
  const nameMap = new Map(
    (existingByName ?? []).map((row) => [normalizeKey(row.name, row.address), row.id]),
  );

  const insertRows = [];
  const updateRows = [];

  for (const row of rows) {
    const exactNameId = nameMap.get(normalizeKey(row.name, row.address));
    const existingId = externalMap.get(row.external_place_id) ?? exactNameId;

    if (existingId) {
      updateRows.push({ id: existingId, row });
    } else {
      insertRows.push(row);
    }
  }

  if (insertRows.length > 0) {
    const { error } = await supabase.from('flower_spots').insert(insertRows);
    if (error) throw error;
  }

  for (const { id, row } of updateRows) {
    const { error } = await supabase
      .from('flower_spots')
      .update({ ...row, updated_at: new Date().toISOString() })
      .eq('id', id);

    if (error) throw error;
  }

  return {
    inserted: insertRows.length,
    updated: updateRows.length,
  };
}

async function main() {
  loadLocalEnv();

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !serviceKey) {
    throw new Error('Required env keys are missing. Check .env.local');
  }

  const supabase = createClient(supabaseUrl, serviceKey, {
    auth: { persistSession: false, autoRefreshToken: false },
  });

  const rows = CURATED_SPOTS.map((spot) => ({
    external_place_id: spot.external_place_id,
    name: spot.name,
    address: spot.address,
    lat: spot.lat,
    lng: spot.lng,
    flower_types: spot.flower_types,
    category: spot.category,
    peak_month_start: spot.peak_month_start,
    peak_month_end: spot.peak_month_end,
    has_night_light: Boolean(spot.has_night_light),
    has_parking: Boolean(spot.has_parking),
    pet_friendly: Boolean(spot.pet_friendly),
    photo_spot: Boolean(spot.photo_spot),
    entry_fee: 0,
    phone: null,
    website_url: null,
    source: 'curated_seed',
  }));

  const result = await syncCuratedSpots(supabase, rows);

  console.log(
    JSON.stringify(
      {
        curatedSpots: rows.length,
        inserted: result.inserted,
        updated: result.updated,
      },
      null,
      2,
    ),
  );
}

main().catch((error) => {
  console.error('[seed:curated] failed:', error);
  process.exit(1);
});
